// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(function() {
    return $('#books tbody tr').each(function() {
      var current, url;
      current = $(this);
      url = current.find("a").attr("href") + "/delete";
      console.log(url);
      return $('<button type="button" class="btn btn-danger">Delete</button>').click(function() {
        return $.ajax(url).done(function() {
          return current.remove();
        });
      }).appendTo(current.find("td:last-child"));
    });
  });

}).call(this);

//# sourceMappingURL=button.map
