// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(function() {
    return $('#books tbody tr').each(function() {
      var currentRow, url;
      currentRow = $(this);
      url = currentRow.find('a:contains("view")').attr("href") + "/delete";
      return $('<button type="button" class="btn btn-danger">Delete</button>').click(function() {
        return $.ajax(url).done(function() {
          return currentRow.remove();
        });
      }).appendTo(currentRow.find("td:last-child"));
    });
  });

}).call(this);

//# sourceMappingURL=button.map
